# Generated by Django 5.2.15 on 2026-06-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icone', models.CharField(choices=[('file-text', 'Fiscal / NF-e'), ('license', 'Registro / CRLV'), ('shield-check', 'Vistoria / Laudo'), ('file-dollar', 'Contrato'), ('package', 'Lote'), ('file', 'Geral')], default='file', max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('padroes_nome', models.TextField(blank=True, help_text='Padrões separados por vírgula (ex: NF-e, DANFE, nota fiscal)')),
                ('extensoes_permitidas', models.CharField(default='pdf,xml,png,jpg,jpeg,xlsx,docx', help_text='Extensões separadas por vírgula', max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassi', models.CharField(blank=True, max_length=17)),
                ('placa', models.CharField(blank=True, max_length=10)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('ano_fabricacao', models.IntegerField(blank=True, null=True)),
                ('ano_modelo', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='documentos.lote')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_original', models.CharField(max_length=255)),
                ('nome_exibicao', models.CharField(blank=True, max_length=255)),
                ('extensao', models.CharField(max_length=10)),
                ('tamanho_bytes', models.BigIntegerField(default=0)),
                ('onedrive_item_id', models.CharField(blank=True, max_length=500)),
                ('onedrive_path', models.CharField(blank=True, max_length=1000)),
                ('onedrive_url', models.URLField(blank=True, max_length=2000)),
                ('onedrive_download_url', models.URLField(blank=True, max_length=2000)),
                ('status_sync', models.CharField(choices=[('pendente', 'Pendente'), ('sincronizado', 'Sincronizado'), ('erro', 'Erro no upload')], default='pendente', max_length=20)),
                ('erro_sync', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Tags separadas por vírgula', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='empresas.empresa')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.lote')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='documentos.tipodocumento')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='documentos.veiculo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['empresa', 'tipo'], name='documentos__empresa_58b6dc_idx'), models.Index(fields=['lote'], name='documentos__lote_id_c2e36b_idx'), models.Index(fields=['status_sync'], name='documentos__status__a8b524_idx')],
            },
        ),
    ]
