# Generated by Django 5.2.15 on 2026-06-15 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('leve', 'Veículos Leves'), ('pesado', 'Veículos Pesados'), ('moto', 'Motos e Especiais'), ('outro', 'Outro')], max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor_hex', models.CharField(default='#378ADD', help_text='Cor para identificação visual', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Veículo',
                'verbose_name_plural': 'Categorias de Veículos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial')], default='matriz', max_length=10)),
                ('razao_social', models.CharField(max_length=200)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='empresas.categoriaveiculo')),
                ('matriz', models.ForeignKey(blank=True, help_text='Preenchido apenas para filiais', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filiais', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_upload', models.BooleanField(default=True)),
                ('pode_excluir', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Empresa',
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
